#!/usr/bin/env python3

""" Kafka To Hbase transfer utility """

import argparse
import os

import kafka2hbase


def dump_config(c):
    """ Dump the current configuration nicely to the console """
    max_width = max(
        len(x)
        for x in c
    )

    output = []

    output.append("Current environment:")
    for k, v in c.items():
        output.append("\t{k: <{fill}}\t{v}".format(k=k, fill=max_width, v=v))

    return "\n".join(output)


config = kafka2hbase.load_config(os.environ)

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
parser.prog = "kafka-to-hbase"
parser.description = "Simple Kafka to Hbase shovel utility"
parser.epilog = dump_config(kafka2hbase.all_env_vars(os.environ))
parser.parse_args()
